package com.sgi.fiis.resolutions.application.usecase;

import com.sgi.fiis.resolutions.domain.model.Resolution;
import com.sgi.fiis.resolutions.domain.port.in.IssueResolutionCommand;
import com.sgi.fiis.resolutions.domain.port.in.IssueResolutionUseCase;
import com.sgi.fiis.resolutions.domain.port.out.DocumentStoragePort;
import com.sgi.fiis.resolutions.domain.port.out.ResolutionRepositoryPort;
import com.sgi.fiis.resolutions.domain.port.out.ProcedureRepositoryPort;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

@Service
public class IssueResolutionService implements IssueResolutionUseCase {

    private final ResolutionRepositoryPort resolutionRepositoryPort;
    private final ProcedureRepositoryPort procedureRepositoryPort;
    private final DocumentStoragePort documentStoragePort;
    private final MessageSource messageSource;

    public IssueResolutionService(ResolutionRepositoryPort resolutionRepositoryPort,
                                  ProcedureRepositoryPort procedureRepositoryPort,
                                  DocumentStoragePort documentStoragePort,
                                  MessageSource messageSource) {
        this.resolutionRepositoryPort = resolutionRepositoryPort;
        this.procedureRepositoryPort = procedureRepositoryPort;
        this.documentStoragePort = documentStoragePort;
        this.messageSource = messageSource;
    }

    @Override
    @Transactional
    public Resolution issue(IssueResolutionCommand command) {
        // 1. Validate that the procedure exists
        if (!procedureRepositoryPort.existsProcedure(command.idTramite())) {
            throw new IllegalArgumentException(
                    messageSource.getMessage("resolution.error.procedure-not-found", null, LocaleContextHolder.getLocale()));
        }

        // 2. Validate that the resolution number is not duplicated
        if (resolutionRepositoryPort.existsByNumber(command.numeroResolucion())) {
            throw new IllegalArgumentException(
                    messageSource.getMessage("resolution.error.duplicate-number", null, LocaleContextHolder.getLocale()));
        }

        // 3. Save the attached document (PDF) through the port
        Long documentId = documentStoragePort.saveDocument(
                command.fileBytes(),
                command.fileName(),
                command.contentType()
        );

        // 4. Create the domain entity
        Resolution newResolution = new Resolution(
                null, // ID will be generated by the DB
                command.numeroResolucion(),
                command.fechaEmision(),
                command.asunto(),
                command.idTramite(),
                documentId,
                LocalDateTime.now(java.time.ZoneId.systemDefault())
        );

        // 5. Save the resolution
        Resolution savedResolution = resolutionRepositoryPort.save(newResolution);

        // 6. Update the procedure status to APROBADO_CON_RESOLUCION
        procedureRepositoryPort.updateStatusToApprovedWithResolution(command.idTramite());

        return savedResolution;
    }
}
