services:
  db_fiis:
    image: postgres:15-alpine
    container_name: sgifiis-postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <-- Ahora lee dinámicamente el .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_fiis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - sgifiis-network

  api_fiis:
    build: .
    container_name: sgifiis-backend-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Configuración de conexión que usará Spring Boot dinámicamente desde el .env
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_fiis:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # Configuración para que Flyway se ejecute automáticamente al arrancar
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      db_fiis:
        condition: service_healthy
    volumes:
      - uploads_fiis_data:/app/uploads-fiis
    networks:
      - sgifiis-network

volumes:
  postgres_fiis_data:
  uploads_fiis_data:

networks:
  sgifiis-network:
    driver: bridge
