services:
  db_fiis_dev:
    image: postgres:15-alpine
    container_name: sgifiis-postgres-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_fiis_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - sgifiis-network-dev

  api_fiis_dev:
    build: .
    container_name: sgifiis-backend-api-dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_fiis_dev:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      db_fiis_dev:
        condition: service_healthy
    volumes:
      - uploads_fiis_data_dev:/app/uploads-fiis
    networks:
      - sgifiis-network-dev

volumes:
  postgres_fiis_data_dev:
  uploads_fiis_data_dev:

networks:
  sgifiis-network-dev:
    name: sgifiis-network-shared
    external: true