spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_fiis_investigacion}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 5MB       # Tamaño máximo permitido por cada archivo individual
      max-request-size: 10MB     # Tamaño máximo total permitido para toda la petición HTTP

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
